### ISSUE TITLE
Application menu shows beta tag icon (safari)

### ISSUE THREAD

**Issue by rydberg-git** [AxisCommunications/fluent-components#108]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

The top bar is showing part of the beta tag when text is truncated in Safari
Not a problem i Chrome

### To reproduce

1. Naviget to https://vms.mysystem.axis.com in the Safari browser

Result: The Beta icon is truncated in the application menu

### Screenshots

<img width="402" alt="image" src="https://github.com/AxisCommunications/fluent-components/assets/83021459/d9041fe2-07e2-4291-9e4d-5d2434234cee">

### Environment

https://vms.mysystem.axis.com in the Safari browser

**Comment by axis-d0op** [comment]
we no longer show beta icon, so i close this
